import { Outfit, Nunito } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],weight: ["400","500","600","700"]
});

const  nunito =  Nunito({
  subsets: ["latin"], weight: ["400"]
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} ${ nunito.className} antialiased leading-8 overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}